### ISSUE TITLE
Multiplicador

### ISSUE THREAD

**Issue by herysantoszup** [diillson/calculador-de-plr#1]
Olá!

No parâmetro `multiplicador`, existe uma tabela ou a relação é direta? ex: Z05 -> 5x

--multiplicador ou -m: Especifica o multiplicador da PLR.

Obrigado pela App!

**Comment by diillson** [comment]
Olá, boa noite, 
o multiplicador é baseado no Zx especifico, ele é um input enviado pelo usuário.
